### ISSUE TITLE
make dependency on numba-scipy optional

### ISSUE THREAD

**Issue by kjyv** [Blue-Yonder-OSS/cyclic-boosting#21]
When importing the pipeline as in the sample, without calling any code I see this:
```
from cyclic_boosting.pipelines import pipeline_CBPoissonRegressor
  File "<...>/lib/python3.10/site-packages/cyclic_boosting/__init__.py", line 40, in <module>
    from cyclic_boosting.nbinom import CBNBinomC
  File "<...>/lib/python3.10/site-packages/cyclic_boosting/nbinom.py", line 9, in <module>
    import numba_scipy.special  # noqa
  File "<...>/lib/python3.10/site-packages/numba_scipy/special/__init__.py", line 1, in <module>
    from . import overloads as _overloads
  File "<...>/lib/python3.10/site-packages/numba_scipy/special/overloads.py", line 4, in <module>
    from . import signatures
  File "<...>/lib/python3.10/site-packages/numba_scipy/special/signatures.py", line 376, in <module>
    ('pdtr', numba.types.float64, numba.types.float64): ctypes.CFUNCTYPE(ctypes.c_double, ctypes.c_double, ctypes.c_double)(get_cython_function_address('scipy.special.cython_special', '__pyx_fuse_0pdtr')),
  File "<...>/lib/python3.10/site-packages/numba/core/extending.py", line 466, in get_cython_function_address
    return _import_cython_function(module_name, function_name)
ValueError: No function '__pyx_fuse_0pdtr' found in __pyx_capi__ of 'scipy.special.cython_special'
```
Python 3.10.5, scipy 1.10.1, macOS 13.3.1

**Comment by FelixWick** [comment]
I assume this is due to a version mismatch between your installed numba-scipy and scipy. Can you try with the versions in https://github.com/Blue-Yonder-OSS/cyclic-boosting/blob/main/poetry.lock?

**Comment by kjyv** [comment]
Well probably you're right numba-scipy 0.3.1 is not compatible with the scipy version so I'd be forced to downgrade to 1.7.3 which is also not compatible with the numpy version we're using. Why require such an old scipy version?

**Comment by FelixWick** [comment]
Because numba-scipy unfortunately requires scipy<=1.7.3

**Comment by kjyv** [comment]
Ah I see. Not sure about your internals, but maybe the numba and numba-scipy dependency can be made optional since numba itself also often lags a bit behind e.g. python updates. We had some issues with not being able to update mlflow because of that, so they're making some dependencies optional now.

**Comment by FelixWick** [comment]
Yeah, in fact it is blocking python 3.11 for us, at the moment. Let me check options. Thanks!

**Comment by kjyv** [comment]
This is still an issue, isn't it?

**Comment by StefanUlbrich** [comment]
Can we get rid of `numba_scipy` alltogether? We need it only to use `gammaln`, and maybe we could manually create an overload for that function. This [post](https://stackoverflow.com/a/63435017) links to a project that does this, and for one single function, we could duplicate the code. I'll have a look at the code to guess the effort it takes

**Comment by FelixWick** [comment]
Yes, we use numba_scipy only for gammaln, and it is only needed in the negative binomial width mode.
I’m fine with replacing it by an own implementation, if we make sure impact on performance is minor.
To your question: x is a positive integer. n is positive, but float.

**Comment by StefanUlbrich** [comment]
Any other constraint that we a have for $n$? I added a notebook to the PR with at quite fast implementation of the Stirling approximation which doesn't seem to be too accurate for $n<2$. Can you have a look at the [new notebook](https://github.com/Blue-Yonder-OSS/cyclic-boosting/blob/contrib/remove_numba_scipy/examples/gammaln_test.ipynb) please and continue the discussion?

**Comment by FelixWick** [comment]
Thanks! Will have a closer look at the notebook.
No, no further constraints.
The precision sounds ok. But yeah, let’s do some variations of the width model integration test and check the impact on c.
And yes, please add a performance test. It sounds like we will be fine here, but this is also very useful in general.

**Comment by FelixWick** [comment]
After having a closer look, I'm in favor of an optional dependency on numba-scipy for users who need nbinom width (with high accuracy).
