### ISSUE TITLE
_init_default_feature_groups does not support X being a ndarray

### ISSUE THREAD

**Issue by rijkvandermeulen** [Blue-Yonder-OSS/cyclic-boosting#28]
Hey guys,

I recently stumbled across you repo; great stuff and thank you for open sourcing this! I really like the idea behind the algorithm - particularly for supply chain demand forecasting.

Perhaps it's due to my inexperience with the library but when I started playing around with it I get the feeling that it's not entirely supporting numpy arrays as data structure. E.g., when you don't pass the `feature_groups ` argument when you instantiate your model (e.g., `CBNBinomRegressor`), it should initialize `feature_groups ` to be a list of all columns available in X, right? However, your `get_feature_column_names ` helper in utils is relying on X being a `pd.DataFrame`. It breaks when you pass a `ndarray`. 

Do you agree? I'd be happy to refactor the `get_feature_column_names ` function and open a PR for this. 

As a more general point, have you thought about type hinting your code (perhaps even with a static type checker like mypy)? In my experience, that makes the code significantly easier to read and would prevent issues such as this one.

Best,
Rijk

**Comment by FelixWick** [comment]
Thank you!
