### ISSUE TITLE
add convenience functionality to access individual factors

### ISSUE THREAD

**Issue by Annaeg** [Blue-Yonder-OSS/cyclic-boosting#29]
Hey,

I recently found your repo, thanks for open-sourcing it!

Perhaps it's due to my inexperience with the library, but the articles you refer to state that you can either use the MAD or MSE for the loss function. In your repo, I can't find which one is used and where to change it.

Another thing I cannot find the option to extract the values for individual factors used for a specific prediction. Is this already implemented or still on your planning?

**Comment by FelixWick** [comment]
Thanks for your interest and questions.
What is implemented in the package is MSE, see [here](https://github.com/Blue-Yonder-OSS/cyclic-boosting/blob/main/cyclic_boosting/base.py#L226). Although using another loss function would be straightforward, it currently requires a code change, unfortunately.
Extracting the values for individual factors used for a specific prediction is possible, please find an example [here](https://github.com/Blue-Yonder-OSS/cyclic-boosting-example/blob/main/cb.py#L40). But I have to admit that it would be nice to make this more accessible :).
