### ISSUE TITLE
Fit and predict methods change X in place

### ISSUE THREAD

**Issue by joshdunnlime** [Blue-Yonder-OSS/cyclic-boosting#62]
Currently, X inputs to methods get modified inplace. This is pretty dangerous! This seems to happen in fit and predict.

Current work around is `.fit(X.copy, y)` but this rather goes against the sklearn pattern.

**Comment by FelixWick** [comment]
You're right. It was a deliberate decision to change X inplace in order to save memory. But I agree, we should not do this anymore.

**Comment by FelixWick** [comment]
The inplace change is due to the binning before the Cyclic Boosting fit/predict in the pipeline. I have implemented a "fix" in the above pull request. As I would make the default "not changing", this will be an interface change. So, it will go to the next release.
